# Generated by Django 4.2.7 on 2024-02-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modelserializer_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="users",
            field=models.CharField(max_length=50),
        ),
    ]
