# Generated by Django 4.2.7 on 2024-02-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modelserializer_app", "0002_alter_account_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="account_url",
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
