# Generated by Django 4.2.7 on 2024-02-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modelserializer_app", "0003_account_account_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="account_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
