# Generated by Django 4.2.7 on 2024-02-09 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modelserializer_app", "0004_alter_account_account_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="account_name",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
