# Generated by Django 4.2.7 on 2024-02-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modelserializer_app", "0005_alter_account_account_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="HighScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("player_name", models.CharField(max_length=10)),
                ("score", models.IntegerField()),
            ],
        ),
    ]
